name: "Deploy Terragrunt"
description: "Deploy Terragunt to the specified environment"

inputs:
  x_access_token:
    description: "Application access token for github"
    required: true
  scw_profile:
    description: "Scaleway porfile"
    required: true
  scw_aws_credentials:
    description: "Scaleway AWS credentials"
    required: true
  scw_credentials:
    description: "Scaleway credentials"
    required: true
  tf_version:
    description: "Terraform version to use"
    required: true
  tg_version:
    description: "Terragrunt version to use"
    required: true
  tg_working_dir:
    description: "Directory in which Terragrunt will be invoked"
    required: true
  tg_command:
    description: "Command to execute"
    required: true

outputs:
  version:
    description: "Build version fetched from git ref"
    value: ${{ steps.fetch-version.outputs.result }}

runs:
  using: "composite"
  steps:
    - uses: gruntwork-io/terragrunt-action@v2
      env:
        AWS_PROFILE: ${{ inputs.scw_profile}}
        SCW_PROFILE: ${{ inputs.scw_profile}}
        # Configure Git to use installation token
        INPUT_PRE_EXEC_1: |
          git config --global url."https://x-access-token:${{ inputs.x_access_token }}@github.com/".insteadOf "https://github.com/"
        # Configure Scaleway and AWS credentials
        INPUT_PRE_EXEC_2: |
          mkdir -p $HOME/.aws
          mkdir -p $HOME/.config/scw
          echo "${{ inputs.scw_aws_credentials }}" > $HOME/.aws/credentials
          echo "${{ inputs.scw_credentials }}" > $HOME/.config/scw/config.yaml
      with:
        tf_version: ${{ inputs.tf_version }}
        tg_version: ${{ inputs.tg_version }}
        tg_dir: ${{ inputs.tg_working_dir }}
        tg_command: ${{ inputs.tg_command }}
