name: 'CalendarVersion'
description: Generates UTC-based CalVer in the format YYYY.mdd.HHMMSS-sha{7 symbols} that is parsable by SemVer

outputs:
  new_version:
    description: "Newly generated version"
    value: ${{ steps.calendar-version.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: calendar-version
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const { generateVersion } = require(`${process.env.GITHUB_ACTION_PATH}/script.js`)
          return generateVersion({ github, context, core });