name: Build a frontend library
on:
  workflow_call:

env:
  HOME: ${{github.workspace}}

jobs:
  build:
    runs-on:
      group: gke-non-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      # Install yarn as we are using a self-hosted runner
      - name: Install Yarn
        run: |
          npm install -g yarn@1.22.22
      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile
#      - name: Run lint
#        run: yarn run lint
      - name: Run build
        run: yarn build
