name: Build a Go microservice and publish it to Docker registry
on:
  workflow_call:
    inputs:
      service_name:
        description: "The service name to be published to Docker registry"
        type: string
        required: true
      app_dir:
        description: "Path to the go.mod file"
        type: string
        default: "."
      skip_linter:
        description: "A boolean flag to skip linter checks"
        type: boolean
        default: false
      generate_docs:
        description: "A boolean flag to generate Swagger docs"
        type: boolean
        default: false
    outputs:
      new-version:
        description: "The new service version"
        value: ${{ jobs.build.outputs.service-version }}

env:
   HOME: ${{github.workspace}}
   CODE_COVERAGE_ARTIFACT: 'code-coverage'

jobs:
  build:
    runs-on:
      group: builder
    outputs:
      service-version: ${{ steps.version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ inputs.app_dir }}/go.mod'
          cache-dependency-path: '${{ inputs.app_dir }}/go.sum'
      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GOLANG_BUILDER_APP_ID }}
          private-key: ${{ secrets.GOLANG_BUILDER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Configure Git to use installation token
        run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"
          printf "${{ secrets.GITLAB_NETRC }}" > ~/.netrc
      - name: Generate swagger docs
        if: ${{ inputs.generate_docs == true }}
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          make swagger
      - name: Install dependencies
        run: make install
      - name: Run build
        run: make build
      - name: Run tests
        run: |
          go test -json -v ./... -cover -coverprofile=coverage.txt | gotestfmt
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CODE_COVERAGE_ARTIFACT }}
          path: coverage.txt
      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        if: ${{ inputs.skip_linter == false }}
        with:
          version: v1.59
          working-directory: ${{ inputs.app_dir }}
      - name: Generate Version
        id: version
        uses: chirpwireless/reusable-github-actions/.github/actions/calendar-version@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ steps.version.outputs.new_version }}

  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: fgrosse/go-coverage-report@v1.1.1
        with:
          coverage-artifact-name: ${{ env.CODE_COVERAGE_ARTIFACT }}
          coverage-file-name: "coverage.txt"

  publish-release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on:
      group: gke-non-prod
    needs: [ build ]
    steps:
      - uses: chirpwireless/reusable-github-actions/.github/actions/publish-release@main
        with:
          version: ${{ needs.build.outputs.service-version }}
