name: Build a Go microservice and publish it to Docker registry
on:
  workflow_call:
    inputs:
      service_name:
        description: "The service name to be published to Docker registry"
        type: string
        required: true
      app_dir:
        description: "Path to the go.mod file"
        type: string
        default: "."
      skip_linter:
        description: "A boolean flag to skip linter checks"
        type: boolean
        default: false
      generate_docs:
        description: "A boolean flag to generate Swagger docs"
        type: boolean
        default: false
    outputs:
      new-version:
        description: "The new service version"
        value: ${{ jobs.build.outputs.new_version }}

env:
   HOME: ${{github.workspace}}

jobs:
  build:
    runs-on:
      group: gke-non-prod
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    env:
      docker_tag: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: version
        uses: chirpwireless/reusable-github-actions/.github/actions/calendar-version@main
      - name: "Create a summary"
        run: |
          echo "Building a new revision ${{steps.version.outputs.new_version}}" > $GITHUB_STEP_SUMMARY
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ inputs.app_dir }}/go.mod'
          cache: false
      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-github-app-token@v1
        id: app-token-chirp-wireless
        with:
          app-id: ${{ secrets.GOLANG_BUILDER_APP_ID }}
          private-key: ${{ secrets.GOLANG_BUILDER_PRIVATE_KEY }}
          owner: 'chirpwireless'
      - uses: actions/create-github-app-token@v1
        id: app-token-chirp-depin
        with:
          app-id: ${{ secrets.CHIRP_DEPIN_BUILDER_APP_ID }}
          private-key: ${{ secrets.CHIRP_DEPIN_BUILDER_PRIVATE_KEY }}
          owner: 'chirpdepin'
      - name: Configure Git to use installation token
        run: |
          git config --global url."https://x-access-token:${{ steps.app-token-chirp-wireless.outputs.token }}@github.com/chirpwireless/".insteadOf "https://github.com/chirpwireless/"
          git config --global url."https://x-access-token:${{ steps.app-token-chirp-depin.outputs.token }}@github.com/chirpdepin/".insteadOf "https://github.com/chirpdepin/"
          printf "${{ secrets.GITLAB_NETRC }}" > ~/.netrc
      - name: Generate swagger docs
        if: ${{ inputs.generate_docs == true }}
        run: |
          (cd ${{inputs.app_dir}} && go get -u github.com/swaggo/swag/cmd/swag && go install github.com/swaggo/swag/cmd/swag)
          make swagger
      - name: Install dependencies
        run: make install
      - name: Run build
        run: make build
      - name: Run tests
        run: |
          cd ${{ inputs.app_dir}} && go test -json -v ./... -cover -coverprofile=coverage.txt | gotestfmt
      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        if: ${{ inputs.skip_linter == false }}
        with:
          version: v1.62.2
          working-directory: ${{ inputs.app_dir }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.docker_tag }}:${{ steps.version.outputs.new_version }}
          cache-from: type=registry,ref=${{ env.docker_tag }}:buildcache
          cache-to: type=registry,ref=${{ env.docker_tag }}:buildcache,mode=max
      - name: Publish Version
        uses: chirpwireless/reusable-github-actions/.github/actions/version-publish@main
        with:
          commit-sha: ${{ github.event.pull_request.head.sha || github.sha }}
          build-version: ${{ steps.version.outputs.new_version }}

  publish-release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on:
      group: gke-non-prod
    needs: [ build ]
    steps:
      - uses: chirpwireless/reusable-github-actions/.github/actions/publish-release@main
        with:
          version: ${{ needs.build.outputs.new_version }}
