name: Build a frontend library
on:
  workflow_call:
    outputs:
      new-version:
        description: "The new service version"
        value: ${{ jobs.generate-version.outputs.service-version }}

env:
  HOME: ${{github.workspace}}

jobs:
  build:
    runs-on:
      group: gke-non-prod
    env:
      publish: ${{github.ref != 'refs/heads/main' || github.ref == 'refs/heads/master'}}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GOLANG_BUILDER_APP_ID }}
          private-key: ${{ secrets.GOLANG_BUILDER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      # Install yarn as we are using a self-hosted runner
      - name: Install Yarn
        run: |
          npm install -g yarn@1.22.22
      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile
#      - name: Run lint
#        run: yarn run lint
      - name: Run build
        run: yarn build
      - name: Bump Version
        if: ${{env.publish == 'true' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          yarn version --minor
      - name: Commit and Push Version Change
        if: ${{env.publish == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --follow-tags
      - name: Publish to NPM
        if: ${{env.publish == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn publish
