name: Deploy a microservice using helmfile

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: "Version to be deployed"
        type: string
      environment:
        required: true
        description: "Environment (k8s namespace)"
        type: string
      deploy_dir:
        required: true
        description: "Path to the helm charts"
        type: string
jobs:
  deploy:
    container:
      image: alpine:3.20.1
    runs-on:
      group: ${{ inputs.environment == 'prod' && 'gke-prod' || 'gke-non-prod'}}
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Install helmfile
        run: |
          curl -L https://github.com/helmfile/helmfile/releases/download/v1.0.0-rc.5/helmfile_1.0.0-rc.5_linux_amd64.tar.gz > helmfile.tar.gz
          tar -xxf helmfile.tar.gz
          rm helmfile.tar.gz
      - name: Deploy using helmfile
        env:
          VERSION: ${{ inputs.version }}
        run: |
          cd ${{ inputs.deploy_dir }} && ../helmfile -e ${{inputs.environment}} -n namespace apply