name: Deploy a microservice using helmfile

on:
  workflow_call:
    inputs:
      version:
        description: "Git reference (branch, tag or SHA) of commit to deploy"
        type: string
      environment:
        required: true
        description: "Environment (k8s namespace)"
        type: string
      deploy_dir:
        required: true
        description: "Path to the helm charts"
        type: string

env:
  HOME: /home/runner

jobs:
  fetch_version:
    runs-on:
      group: gke-non-prod
    outputs:
      version: ${{steps.fetch-version.outputs.version}}
    steps:
      - id: fetch-version
        uses: chirpwireless/reusable-github-actions/.github/actions/version-fetch@feature/deploy-from-latest
        with:
          git-ref: ${{ inputs.version }}
      - run: |
          echo "Deploying the version ${{steps.fetch-version.outputs.version}}" > $GITHUB_STEP_SUMMARY

  deploy:
    name: "Deploy to ${{inputs.environment}}"
    needs: fetch_version
    runs-on:
      group: ${{ inputs.environment == 'prod' && 'gke-prod' || 'gke-non-prod'}}
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy using helmfile
        env:
          VERSION: ${{ needs.fetch_version.outputs.version }}
        run: |
          cd ${{ inputs.deploy_dir }} && helmfile -e ${{inputs.environment}} -n ${{inputs.environment}} apply
