name: Deploy a Terraform with Terragrunt
on:
  workflow_call:
    inputs:
      version:
        description: "Git reference (branch, tag or SHA) of commit to deploy"
        type: string
      environment:
        required: true
        description: "Environment (Terraform environment)"
        type: string
      tf_version:
        description: "Terraform version to use"
        type: string
        default: "1.10.3"
      tg_version:
        description: "Terragrunt version to use"
        type: string
        default: "0.71.1"
      tg_working_dir:
        description: "Directory in which Terragrunt will be invoked"
        type: string
        required: true

env:
  HOME: ${{github.workspace}}

jobs:
  prepare:
    runs-on:
      group: scw-k8s-dev
    outputs:
      version: ${{steps.fetch-version.outputs.version}}
      scw_profile: ${{ steps.setup.outputs.scw_profile }}
    steps:
      - id: fetch-version
        uses: chirpwireless/reusable-github-actions/.github/actions/version-fetch@main
        with:
          git-ref: ${{ inputs.version }}

      - name: "Create a summary"
        run: |
          echo "Deploying the version ${{steps.fetch-version.outputs.version}}" > $GITHUB_STEP_SUMMARY

      - name: Setup profile
        id: setup
        run: |
          # Check if the input matches any of the expected values
          if [[ "${{ inputs.tg_working_dir }}" == "live/non-prod/"* ]]; then
              echo "scw_profile=chirp-non-prod" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.tg_working_dir }}" == "live/prod/"* ]]; then
              echo "scw_profile=chirp-prod" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.tg_working_dir }}" == "live/kiloiot/"* ]]; then
              echo "scw_profile=kiloiot" >> $GITHUB_OUTPUT
          else
              echo "Unknown profile for the path: ${{ inputs.tg_working_dir }}"
              exit 1  # Fail the job if the path is unknown
          fi

  plan:
    name: "Plan deploy to ${{inputs.environment}}"
    needs: [prepare]
    runs-on:
      group: scw-k8s-dev
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.version }}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GOLANG_BUILDER_APP_ID }}
          private-key: ${{ secrets.GOLANG_BUILDER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Create a deploy plan using Terragrunt
        uses: chirpwireless/reusable-github-actions/.github/actions/deploy-terragrunt@main
        with:
          x_access_token: ${{ steps.app-token.outputs.token }}
          scw_profile: ${{ needs.prepare.outputs.scw_profile}}
          scw_aws_credentials: ${{ secrets.SCW_AWS_CREDENTIALS }}
          scw_credentials: ${{ secrets.SCW_CREDENTIALS }}
          tf_version: ${{ inputs.tf_version }}
          tg_version: ${{ inputs.tg_version }}
          tg_working_dir: ${{ inputs.tg_working_dir }}
          tg_command: "run-all plan"

  deploy:
    name: "Deploy to ${{inputs.environment}}"
    needs: [prepare, plan]
    runs-on:
      group: scw-k8s-dev
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.version }}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GOLANG_BUILDER_APP_ID }}
          private-key: ${{ secrets.GOLANG_BUILDER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Deploy using Terragrunt
        uses: chirpwireless/reusable-github-actions/.github/actions/deploy-terragrunt@main
        with:
          x_access_token: ${{ steps.app-token.outputs.token }}
          scw_profile: ${{ needs.prepare.outputs.scw_profile}}
          scw_aws_credentials: ${{ secrets.SCW_AWS_CREDENTIALS }}
          scw_credentials: ${{ secrets.SCW_CREDENTIALS }}
          tf_version: ${{ inputs.tf_version }}
          tg_version: ${{ inputs.tg_version }}
          tg_working_dir: ${{ inputs.tg_working_dir }}
          tg_command: "run-all apply"
