name: Deploy a microservice using helmfile

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: "Version to be deployed"
        type: string
      environment:
        required: true
        description: "Environment (k8s namespace)"
        type: string
      deploy_dir:
        required: true
        description: "Path to the helm charts"
        type: string

env:
  HOME: /home/runner

jobs:
  deploy:
    container:
      image: ghcr.io/chirpwireless/docker/actions-deployer-runner-image:feature-initial-eeaa612
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    runs-on:
      group: ${{ inputs.environment == 'prod' && 'gke-prod' || 'gke-non-prod'}}
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: helmfile/helmfile-action@v1.9.1
        env:
          VERSION: ${{ inputs.version }}
        with:
          helmfile-workdirectory: ${{ inputs.deploy_dir }}
          helmfile-args: apply --environment ${{ inputs.environment }}
      - name: Deploy using helmfile
        env:
          VERSION: ${{ inputs.version }}
        run: |
          cd ${{ inputs.deploy_dir }} && ../helmfile -e ${{inputs.environment}} -n namespace apply